name: 'Test'

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build TypeScript packages
        run: pnpm run build:ts
      - name: Run unit tests
        run: pnpm run test:jest:core
